apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- name: camel-integration-capability-config
  behavior: merge
  literals:
  # Set me!
  #- git-repo-url=http://github.com/<org>/<repo>
  - grpc-port=9190
  - registration-url=http://wanaku-router-backend:8080
  - registration-announce-address=auto
  - service-name=camel-core-downstream-dev
  # Set me!! Cannot run without these
  # - routes-path=/data/<repo>/route.camel.yaml
  # - routes-rules=/data/<repo>/route-rules.yaml

secretGenerator:
- name: camel-integration-capability-secrets
  behavior: merge
  literals:
  - client-id=wanaku-service
  # Add your dev secrets here or use --from-file
  # - client-secret=dev-secret
  # - token-endpoint=http://keycloak:8080/realms/wanaku/

replicas:
- name: camel-integration-capability
  count: 1

images:
# Configure the main application image
- name: quay.io/wanaku/camel-integration-capability
  newName: quay.io/wanaku/camel-integration-capability
  newTag: latest
# Configure the git init container image. You have to build this!
- name: quay.io/my-org/git-init-container:latest
  newName: quay.io/my-org/git-init-container:latest
  newTag: latest
